/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSeas: typeof import('./src/components/HomePage/AboutSeas.vue')['default']
    Activities: typeof import('./src/components/Coordination/Activities.vue')['default']
    Button: typeof import('primevue/button')['default']
    CollecHeader: typeof import('./src/components/Collection/CollecHeader.vue')['default']
    CompiHeader: typeof import('./src/components/Compilation/CompiHeader.vue')['default']
    CoorActivity: typeof import('./src/components/Coordination/CoorActivity.vue')['default']
    CoorDirectoryHeader: typeof import('./src/components/Coordination/CoorDirectoryHeader.vue')['default']
    CoorHeader: typeof import('./src/components/Coordination/CoorHeader.vue')['default']
    DataIndicators: typeof import('./src/components/HomePage/DataIndicators.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Header: typeof import('./src/components/Coordination/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeCalendar: typeof import('./src/components/HomePage/HomeCalendar.vue')['default']
    HomeHeader: typeof import('./src/components/HomePage/HomeHeader.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ProceHeader: typeof import('./src/components/Processing/ProceHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SideNavBar: typeof import('./src/components/HomePage/SideNavBar.vue')['default']
    StockholderDirectory: typeof import('./src/components/Coordination/StockholderDirectory.vue')['default']
    StockHolderDirectory: typeof import('./src/components/Coordination/StockHolderDirectory.vue')['default']
    TotalDataCollected: typeof import('./src/components/HomePage/TotalDataCollected.vue')['default']
    UtilHeader: typeof import('./src/components/Utility/UtilHeader.vue')['default']
  }
}
